### ISSUE TITLE
Increase log retention time for Stackdriver

### ISSUE THREAD

**Issue by anniekuan** [CancerDataAggregator/cda-service#106]
Leadership team would like to be able to see user queries and user metrics (e.g. number of unique users using CDA, number of queries per day, etc.). Should already be available through Stackdriver implementation, but currently only retains logs for 30 days. Ideally we can increase the log retention time or we can store it separately in BQ indefinitely (preferable).

**Comment by ACharbonneau** [comment]
We should see what analytics we can get through the broad setup

**Comment by ACharbonneau** [comment]
adding this to the jira backlog
