### ISSUE TITLE
CDA base docker image must derived from blessed security scanned appsec repo

### ISSUE THREAD

**Issue by fkaufman-asym** [CancerDataAggregator/cda-service#123]
Update base docker image for the SpringBoot app from the appsec blessed repo.
https://github.com/broadinstitute/dsp-appsec-blessed-images

**Comment by fkaufman-asym** [comment]
![image](https://user-images.githubusercontent.com/84089414/141532330-29b92107-c9fc-4b16-be2a-c6bc040fe10b.png)

**Comment by ACharbonneau** [comment]
moving to jira backlog
