### ISSUE TITLE
Add endpoint for "distinct values for this column"

### ISSUE THREAD

**Issue by ghost** [CancerDataAggregator/cda-service#19]
Supply user with an endpoint `/api/v1/unique_values/{column_name}` that takes as query parameter a column name and returns all the distinct values for that column

1. Add endpoint to API spec
2. Implement in server code

Example Python code is: https://github.com/CancerDataAggregator/translator-prototype/blob/0587294adfd649c129e93e9c47d9022a000b7a79/queryt/queryt.py#L92

@pshapiro4broad I tagged you on this one because I'm running short of time. If you don't have the bandwidth, no problem.

**Comment by fkaufman-asym** [comment]
Issue fixed
