### ISSUE TITLE
implement actual bigquery status check

### ISSUE THREAD

**Issue by pshapiro4broad** [CancerDataAggregator/cda-service#36]
The system status endpoint includes a big query status result, but it doesn't actually check bigquery to see if it can access it. When implementing this, the result of the status must be cached to avoid calling bigquery too often, since the status endpoint is used by kubernetes to check the health of cda-service. One way to do this is to make it `Cacheable`. or to only refresh the bq status on a timer.

**Comment by ACharbonneau** [comment]
this is done
