### ISSUE TITLE
REST API overwrites/masks unnested data and adds it at top level

### ISSUE THREAD

**Issue by ianfore** [CancerDataAggregator/cda-service#65]
In some ways this is an artifact of the issue described at https://github.com/CancerDataAggregator/cda-python/issues/16. 

Investigated the masking problem at the end of [this notebook](https://github.com/ianfore/cdatest/blob/main/SQL%20Exploration.ipynb) and identified that it occurs within the REST API.
Besides masking, the columns from the nested tables are listed as attributes of the root (patient).

If [the issue above](https://github.com/CancerDataAggregator/cda-python/issues/16) were fixed (likely in cda-client) perhaps this issue would not occur. However, given that the REST API takes SQL, and that the SQL passed to it is legal, perhaps the issue should be addressed. BigQuery presumably returns both the root columns and the nested columns, so the issue likely  arises in how the BigQuery results are handled by the CDA API implementation.

**Comment by pshapiro4broad** [comment]
As commented in https://github.com/CancerDataAggregator/cda-python/issues/16, this appears to be a bug in the service layer code and shouldn't require changes to the python bindings.

**Comment by pshapiro4broad** [comment]
Here's a boolean_query that can be used to test this issue:
```json
{"node_type":"=",
  "l":{
    "node_type":"column",
    "value":"ResearchSubject.Diagnosis.id"
  },
  "r":{
    "node_type":"quoted",
    "value":"2cd3fcac-022c-5750-adfa-96d181e483ea"
  }
}
```
