### ISSUE TITLE
Resolve case sensitivity for query fields

### ISSUE THREAD

**Issue by anniekuan** [CancerDataAggregator/cda-service#70]
Release 1 tester feedback

**Comment by pshapiro4broad** [comment]
(non-legacy) BigQuery SQL doesn't directly support case insensitive search. The usual SQL way around this is to convert both sides of the comparison expression to upper or lower case. For example, `WHERE LOWER(gender) = LOWER('Male')`. https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#lower

There are a number of ways this can be added to the boolean query API. Or we may want a global flag to make all comparisons case insensitive, or default all comparisons to case insensitive search.
