### ISSUE TITLE
Add ability to query inexact values

### ISSUE THREAD

**Issue by anniekuan** [CancerDataAggregator/cda-service#71]
For example, Currently, we can do query such as primary_disease_type= ‘Breast Invasive Carcinoma'. 
Ideally, we should be able to do the following queries:
primary_disease_type ~=/* Breast*/ ?
primary_disease_type ~=/* Carcinoma*/ ?

**Comment by pshapiro4broad** [comment]
This can be done by adding support to the boolean query API for the SQL `CONTAINS` operator. It can be used as an operator between a column and a text literal, e.g., `WHERE primary_disease_type CONTAINS 'Breast'`. In the python layer, we'd have to add a function for this to generate the boolean query.

**Comment by ACharbonneau** [comment]
We have this now! use the wildcard `%`
