### ISSUE TITLE
Need to create an injectable service for BigQuery to enable unit testing of QueryService

### ISSUE THREAD

**Issue by pshapiro4broad** [CancerDataAggregator/cda-service#72]
The `QueryService` class has grown in complexity and would benefit from unit test coverage. Since it directly constructs a BigQuery service object, mocking out the BigQuery connection is not currently possible.

**Comment by pshapiro4broad** [comment]
This should also support a configuration property that defines the BigQuery project and dataset name. The table name, which is the data version, should still configured separately.

**Comment by ACharbonneau** [comment]
Think this isn't needed anymore
