### ISSUE TITLE
File details are repeated within multiple specimens and subjects within a query

### ISSUE THREAD

**Issue by ianfore** [CancerDataAggregator/cda-service#79]
See the [attached.pdf](https://github.com/CancerDataAggregator/cda-service/files/6503780/File.duplication.pdf) of a Jupyter notebook demonstrating the issue. 

This derives from the GDC/ CCDH model as much as the API.

**Comment by YeastCell** [comment]
Hi @ianfore,
we are working on the release 2 currently and it seems like that the majority of concerns you have raised is going to be addressed by linking **File** entity to the **ResearchSubject** and **Patient** entities in addition. We are working on this iteratively and hope to focus more on the "other end of the relationship" (dedicated File table) after the release. For now, working with files located under entities higher in the hierarchy should lift the issues with duplicates.

**Comment by ianfore** [comment]
I can see that in v2 the File is linked to the ResearchSubject and Subject (formerly Subject) entities. That actually makes things worse. The files are now linked to two more objects that previously.

The problem is that it is not possible to understand what the File applies to. You can't even tell whether the file is from tumor or normal, surgery or follow up etc. You can only tell that when the file is nested within the object to which it applies- the is usually the object which it is derived from.  

I'll work on an example.

(I'll leave aside for now the question of files derived from multiple specimens. That requires different consideration).

**Comment by ACharbonneau** [comment]
This should be fixed with the new endpoint setup in release 3
