### ISSUE TITLE
Replace manual validation of openapi inputs with openapi validation

### ISSUE THREAD

**Issue by pshapiro4broad** [CancerDataAggregator/cda-service#80]
`QueryService` manually validates `offset` and `limit`. Instead it should use the openapi `minimum:` tag in the openapi YAML. Once this is added, the validation code can be removed from `QueryService`.

> FWIW, I tend to like to use the preconditions lib for things like this.  Just a touch more concise.  Also, this may be something to pull into a validator class if you end up needing this for other endpoints

_Originally posted by @nmalfroy in https://github.com/CancerDataAggregator/cda-service/pull/76#r636104730_

**Comment by ACharbonneau** [comment]
@rfricke-asymmetrik is this a thing that happened? does it still apply?

**Comment by rfricke-asymmetrik** [comment]
@ACharbonneau this has not been done yet. There is still code in the QueryService to check for a minimum value of offset and limit.

**Comment by ACharbonneau** [comment]
moving to jira backlog
